### ISSUE TITLE
hdf5 mpiio error on the MPI branch.

### ISSUE THREAD

**Issue by rainwoodman** [sigbjobo/hPF_MD_PMESH#1]
Hi,

I encountered this error when trying to run the MPI branch (via ex.sh):

```
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    f_input = h5py.File(sys.argv[2], 'r',driver='mpio', comm=MPI.COMM_WORLD)
  File "/home/yfeng1/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 405, in __init__
    fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds)
  File "/home/yfeng1/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 135, in make_fapl
    set_fapl(plist, **kwds)
  File "/home/yfeng1/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 48, in _set_fapl_mpio
    plist.set_fapl_mpio(**kwargs)
AttributeError: 'h5py.h5p.PropFAID' object has no attribute 'set_fapl_mpio'

```

Do I need to install a special version of hdf5 or h5py to enable the MPI support, or is there a conda package that I can install? 

I usually use github.com/rainwoodman/bigfile for MPI IO - both because I wrote it and also because it is much easier to package & deploy. 
hdf5-mpi used to be tricky in this regard. I wonder if the situation has improved in recent years...

**Comment by sigbjobo** [comment]
I, think i forgot tp update ex.sh. To run:
Mpirun python3 CONF.PY input.hdf5

Yes it is a little hassle, one has to configure for mpi. Bigfile does not need that? Sounds ver nice! (Ps I only have access to mobile during a trip atm, so a bit short answer)

**Comment by sigbjobo** [comment]
ex.sh has now been corrected. Should be easier to run now!

**Comment by rainwoodman** [comment]
Thanks. I still need to set up hdf5 MPI. Is there an instruction that you have followed? 

No bigfile doesn't need reconfigure -- in the python implementation of bitfile, MPI is handled by mpi4py. I think it is ready to use after 'pip install bigfile' (may need cython).

Writing a data column,
```
with bigfile.FileMPI('path/to/file', comm=MPI.COMM_WORLD) as bf:
   bf.create_from_array("Position", local_pos_on_this_rank)
```

and reading a data column
```
with bigfile.FileMPI('path/to/file', comm=MPI.COMM_WORLD) as bf:
# or with bigfile.File('path/to/file') as bf:
   with bf["Position"] as bb:
     local_start = bb.size * comm.rank // comm.size
     local_end = bb.size * (comm.rank + 1) // comm.size
     local_pos = bb[local_start:local_end]
```

**Comment by sigbjobo** [comment]
Yes, should maybe have written it using bigfile, but I noticed too late. I am not entire sure how to install the parallel version, the people working on the computer cluster did it for me.

There is a guide here: 
https://docs.h5py.org/en/stable/mpi.html

I think one can download h5py from:
https://github.com/h5py/h5py

Then the hdf5 can be downloaded:
https://portal.hdfgroup.org/display/support/HDF5+1.8.21#files

Should not be so hard to install, but I am not the best on installing packages, so did not manage yet.

**Comment by rainwoodman** [comment]
Thanks. Your cluster has good support.

The MPI build is probably still conflicting with the non-mpi h5py. I'll give this a go this weekend.

**Comment by sigbjobo** [comment]
[This at least worked for my coworker (mac). ](https://github.com/sigbjobo/hPF_MD_PMESH/tree/MPI#mpi-configured-h5py)

**Comment by sigbjobo** [comment]
Did you try out the guide? Otherwise I will consider making a serial input output option.
