### ISSUE TITLE
h5py fails array slicing with lazy range iterator

### ISSUE THREAD

**Issue by mortele** [sigbjobo/hPF_MD_PMESH#8]
In `main.py` the line

```python
p_mpi_range = range(np_cum_mpi[0],np_cum_mpi[1])
```

causes `h5py` to fail with the following message

```
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    r=f_input['coordinates'][-1,p_mpi_range,:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 776, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/usr/local/lib/python3.8/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 269, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 210, in h5py._selector.Selector.apply_args
TypeError: Simple selection can't process range(0, 166)
```

This only happens on my local installation and not on the cluster. However, it might be good to just change this to be an explicit list as:

```python
p_mpi_range = list(range(np_cum_mpi[0],np_cum_mpi[1]))
```
Unless you are running simulations with *very* large number of particles per process, this will not cause any memory issues and should behave identically on the cluster.

**Comment by sigbjobo** [comment]
I have included your suggestion in my latest commit. The code still runs fine on the cluse. I therefore close this issue.

**Comment by rainwoodman** [comment]
If this is a contiguous chunk, using a slice is usually more efficient.

s = slice(a, b)
dataset[s], perhaps dataset[s][:]
